version: "3.9"

services:
  jenkins-master:
    image: jenkins/jenkins:lts-jdk17
    container_name: jenkins-master
    privileged: true
    ports:
      - "50001:8080"
      - "50002:50000"
    volumes:
      - ./jenkins_data:/var/jenkins_home
      - ./executors.groovy:/usr/share/jenkins/ref/init.groovy.d/executors.groovy # Start with no executors
      - /var/run/docker.sock:/var/run/docker.sock # Builds docker images  & containers from withing Jenkins Container.
    environment:
      # - JENKINS_SLAVE_AGENT_PORT=${JENKINS_SLAVE_AGENT_PORT}
      - JENKINS_OPTS=${ENABLE_ACCESS_LOGS}
      # - JAVA_OPTS=${SKIP_INITIAL_SETUP} # Skip intial setup wizard (If using automation)
      - TZ=${TIME_ZONE}
    user: jenkins
    networks:
      - jenkins-net
    depends_on:
      - nginx-docker

  jenkins-agent:
    image: jenkins/ssh-agent:jdk17
    container_name: jenkins-agent-1
    privileged: true
    # user: jenkins (default)
    expose:
      - 22
    environment:
      - JENKINS_AGENT_NAME=jenkins-agent-1
      - JENKINS_AGENT_SSH_PUBKEY=${PUB_KEY}
    networks:
      - jenkins-net
    depends_on:
      - jenkins-master

  nginx:
    build:
      context: ./nginx-docker
      dockerfile: Dockerfile
    container_name: jenkins-rproxy
    ports:
      - "80:80"
    networks:
      - jenkins-net

volumes:
  jenkins_data:

networks:
  jenkins-net:
    external:
      true