version: "3.9"

services:
  jenkins-master:
    image: jenkins/jenkins:lts
    container_name: jenkins-master
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - JENKINS_SLAVE_AGENT_PORT=50000
      - JENKINS_OPTS= \
        "--prefix=/jenkins" \
        "--accessLoggerClassName=winstone.accesslog.SimpleAccessLogger" \
        "--simpleAccessLogger.format=combined" \
        "--simpleAccessLogger.file=/var/jenkins_home/logs/access_log"
    secrets:
      - jenkins_secrets
    networks:
      - jenkins-net

  jenkins-slave:
    image: jenkins/jnlp-slave:4.11-1
    container_name: jenkins-slave
    environment:
      - JENKINS_URL=http://jenkins-master:8080/jenkins
      - JENKINS_SECRET=<secret-goes-here>
      - JENKINS_AGENT_NAME=<agent-name-goes-here>
      - JENKINS_AGENT_WORKDIR=/home/jenkins/agent
    secrets:
      - jenkins_secrets
      - jenkins-agent-name
    networks:
      - jenkins-net

volume:
  jenkins_home:

networks:
  jenkins-net:
